/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {


    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    tutorialSidebar: [
        {
            type: 'category',
            label: 'Quick Start Guide',
            link: {
                type: 'doc',
                id: 'Quick_Start/getting_started'
            },
            collapsed: false,
            items: [
                {
                    type: 'doc',
                    id: 'Integrations/os/linux/sfagent_linux',
                    label: 'Monitor a Linux system',
                },
                {
                    type: 'doc',
                    id: 'Integrations/os/windows/sfagent_windows',
                    label: 'Monitor a Windows system',
                },
                {
                    type: 'doc',
                    id: 'Quick_Start/sfpoller_setup',
                    label: 'Monitor Cloud Services',
                },
                {
                    type: 'doc',
                    id: 'Integrations/kubernetes/kubernetes_monitoring_with_sfPod',
                    label: 'Monitor a Kubernetes cluster',
                },
                {
                    type: 'category',
                    label: 'Setup SnappyFlow Self Hosted',
                    link: {
                        type: 'generated-index', 
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Quick_Start/aws',
                            label: 'AWS',
                        },
                        {
                            type: 'doc',
                            id: 'Quick_Start/azure',
                            label: 'Azure',
                        } 
                    ], 
                },
               
            ],
        },
        {
            type: 'category',
            label: 'sfPoller',
            link: {
                type: 'doc',
                id: 'sfPoller/overview'
            },
            collapsed: true,
            items: [
                {
                    type: 'doc',
                    id: 'sfPoller/overview',
                    label: 'sfPoller overview',
                },
                {
                    type: 'doc',
                    id: 'sfPoller/aws_setup',
                    label: 'Setup in AWS',
                },
                {
                    type: 'doc',
                    id: 'sfPoller/vcenter_setup',
                    label: 'Setup in vCenter',
                },
                {
                    type: 'doc',
                    id: 'sfPoller/azure_setup',
                    label: 'Setup in Azure',
                }
            ],
        },
        {
            type: 'category',
            label: 'Tracing',
            link: {
                type: 'generated-index',
                title: 'Tracing in SnappyFlow',
                description: 'SnappyFlow supports distributed tracing compliant with Opentracing standard. Tracing allows users to visualize the sequence of steps a transaction (whether API or non-API such as a Celery job) takes during its execution. This analysis is extremely powerful and allows pinpointing the source of problems such as abnormal time being spent on an execution step or identifying point of failure in a transaction. SnappyFlow refers to distributed tracing as sfTrace.',
            },
            collapsed: true,
            items: [ 
				{
                    type: 'category',
                    label: 'Java',
                    link: {
                            type: 'doc',
                            id: 'Tracing/java/overview',
                          },
                    collapsed: true,
                    items: [
                       {
                          type: 'doc',
                          id: 'Tracing/java/instance',
                          label: 'Instance',
                        },
				        {
                          type: 'doc',
                          id: 'Tracing/java/docker',
                          label: 'Docker',
                        },
				        {
                          type: 'doc',
                          id: 'Tracing/java/ecs',
                          label: 'ECS',
                        },
			            {
                          type: 'doc',
                          id: 'Tracing/java/kubernetes',
                          label: 'Kubernetes',
                       },
				       {
                          type: 'doc',
                          id: 'Tracing/java/capture_request_body',
                          label: 'Capture Request Body',
                       },
			           {
                          type: 'doc',
                          id: 'Tracing/java/log_correlation',
                          label: 'Log Correlation',
                       },
			       ],
                },
                {
                    type: 'doc',
                    id: 'Tracing/python',
                    label: 'Python'
                },
                {
                    type: 'doc',
                    id: 'Tracing/ruby',
                    label: 'Ruby'
                },
                {
                    type: 'doc',
                    id: 'Tracing/nodejs',
                    label: 'NodeJS'
                },
                {
                    type: 'category',
                    label: 'C#',
                    link: {
                        type: 'doc',
                        id: 'Tracing/csharp',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Tracing/aspdotnetcore',
                            label: 'ASP.NET Core',
                        },
                        {
                            type: 'doc',
                            id: 'Tracing/dotnetframework',
                            label: '.NET Framework',
                        },
                    ]
                },
                {
                    type: 'doc',
                    id: 'Tracing/go',
                    label: 'GO'
                },
                {
                    type: 'category',
                    label: 'Advanced Tracing Feature',
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Tracing/advanced/trace_history',
                            label: 'Trace History',
                        }
                    ]
                },
				{
                    type: 'category',
                    label: 'Python',
                    link: {
                        type: 'doc',
                        id: 'Tracing/python/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Tracing/python/python_on_instance',
                            label: 'Instance',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/python/python_in_kubernetes',
                            label: 'Kubernetes',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/python/python_in_ECS',
                            label: 'ECS',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/python/python_in_docker',
                            label: 'Docker',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/python/aws_lamda',
                            label: 'AWS Lambda',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/python/capture_request_body_from_trace',
                            label: 'Capture Request Body',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/python/log_correlation',
                            label: 'Log Correlation',
                        },
						
					],
				},
                {
                    type: 'category',
                    label: 'PHP',
                    link: {
                        type: 'doc',
                        id: 'Tracing/php/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Tracing/php/instance',
                            label: 'Instance',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/php/docker',
                            label: 'Docker',
                        },
						{
                            type: 'doc',
                            id: 'Tracing/php/ecs',
                            label: 'ECS',
                        },
                    ],
                },				
            ],


        },
        {
            type: 'category',
            label: 'Integrations',
            link: {
                type: 'doc',
                id: 'Integrations/overview'
            },
            collapsed: true,
            items: [
                {
                    type: 'doc',
                    id: 'Integrations/activemq',
                    label: 'ActiveMQ',
                },
                {
                    type: 'doc',
                    id: 'Integrations/apache/overview',
                    label: 'Apache',
                },
                {
                    type: 'doc',
                    id: 'Integrations/aws_lambda',
                    label: 'AWS Lambda',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/aws',
                    label: 'AWS',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/rds',
                    label: 'AWS RDS',
                },
				{
                    type: 'doc',
                    id: 'Integrations/plugin/auroraDB',
                    label: 'AuroraDB',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/azuredb',
                    label: 'AzureDB',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/azurelog',
                    label: 'AzureLog',
                },
              
                {
                    type: 'doc',
                    id: 'Integrations/plugin/blazemeter',
                    label: 'Blaze Meter',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/blob',
                    label: 'Blob',
                },
                {
                    type: 'category',
                    label: 'Clickhouse',
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/clickhouse_kubernetes',
                            label: 'Clickhouse on Kubernetes',
                        },
                    ]
                },
				{
                    type: 'doc',
                    id: 'Integrations/cloudwatch',
                    label: 'CloudWatch',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/configUpdate',
                    label: 'Configuration Update',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/docker_monitoring',
                    label: 'Docker Monitoring',
                },
                {
                    type: 'doc',
                    id: 'Integrations/elasticache/elasticache',
                    label: 'ElastiCache',
                },
                {
                    type: 'doc',
                    id: 'Integrations/docdb/DocDB',
                    label: 'DocDB',
                },
                {
                    type: 'doc',
                    id: 'Integrations/ecs',
                    label: 'ECS',
                },
                {
                    type: 'doc',
                    id: 'Integrations/elb/elb_rds',
                    label: 'Elastic Load Balancer',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/elb',
                    label: 'ELB',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/elblogs',
                    label: 'ELB Logs',
                },
                {
                    type: 'category',
                    label: 'GO',
                    link: {
                        type: 'doc',
                        id: 'Integrations/go/profiler',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/go/profiler',
                            label: 'Go Profiler',
                        },
                    ],
                },
                {
                    type: 'doc',
                    id: 'Integrations/haproxy',
                    label: 'HAProxy',
                },
                {
                    type: 'doc',
                    id: 'Integrations/hcp_consul',
                    label: 'HCP Consul',
                },
                {
                    type: 'category',
                    label: 'IIS',
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/iis/iis_windows',
                            label: 'IIS in Windows'
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/iis/iis_setup',
                            label: 'IIS Web Server and Access Logging Setup'
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'JAVA',
                    link: {
                        type: 'doc',
                        id: 'Integrations/java/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/java/java_instances',
                            label: 'Monitoring JAVA on Instances',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/java/java_kubernetes',
                            label: 'Monitoring JAVA in Kubernetes',
                        },
                        {
                            type: 'category',
                            label: 'ECS',
                            link: {
                                type: 'generated-index',
                                title: 'ECS Monitoring',
                                // description: 'SnappyFlow provides the two types of agents which help you to collect the application metrics like JVM metrics and tracing.',
                                // type:'doc',
                                // id: 'Integrations/java/ecs_overview',
                                // label: 'ECS Overview',
                            },
                            collapsed: true, 
                            items:[
                                {
                                    type: 'doc',
                                    id: 'Integrations/java/java_ecs_fargate',
                                    label: 'Fargate',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/java/java_ecs_ec2',
                                    label: 'EC2',
                                },
                            ]
                        },
                       
                        {
                            Profiler: [
                                {
                                    type: 'doc',
                                    id: 'Integrations/java/java_profiler_cpu',
                                    label: 'CPU',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/java/java_profiler_memory',
                                    label: 'Memory',
                                },
                            ],

                        },
                    ],
                },
                {
                    type: 'doc',
                    id: 'Integrations/jboss',
                    label: 'JBoss',
                },
                {
                    type: 'category',
                    label: 'Kafka',
                    link: {
                        type: 'doc',
                        id: 'Integrations/kafka/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/kafka/kafka_kubernetes',
                            label: 'Kafka in Kubernetes'
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/kafka/kafka_instances',
                            label: 'Kafka on Instances',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Kubernetes',
                    link: {
                        type: 'doc',
                        id: 'Integrations/kubernetes/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/kubernetes/kubernetes_monitoring_with_sfPod',
                            label: 'Kubernetes Monitoring with sfPod',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/kubernetes/sfkubeagent_installation',
                            label: 'Monitoring Application Pods with sfKubeAgent',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/kubernetes/prometheus_exporter',
                            label: 'Prometheus Exporter',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/kubernetes/centralized_logging_of_application_pod_logs',
                            label: 'Centralized Logging of Application Pods',
                        },
                    ],
                },
                {
                    type: 'doc',
                    id: 'Integrations/mongodb',
                    label: 'MongoDB',
                },
                {
                    type: 'category',
                    label: 'MS SQL',
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/mssql_windows',
                            label: 'MS SQL on Instances',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/plugin/mssql',
                            label: 'MS SQL in Kubernetes',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'MySQL',
                    link: {
                        type: 'doc',
                        id: 'Integrations/mysql/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/mysql/mysql_instances',
                            label: 'MySQL on Instances',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/mysql/mysql_kubernetes',
                            label: 'MySQL in Kubernetes',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/mysql/mysql_windows',
                            label: 'MySQL on Windows',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/mysql/mysql_sfpoller',
                            label: 'MySQL with sfPoller',
                        },
                    ],
                }, 
                {
                    type: 'category',
                    label: 'Nginx',
                    link: {
                        type: 'doc',
                        id: 'Integrations/nginx/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/nginx/nginx_instance',
                            label: 'Monitoring Nginx on Instances',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/nginx/nginx_kubernetes',
                            label: 'Monitoring Nginx in Kubernetes',
                        },
                    ],
                },
                {
                    type: 'doc',
                    id: 'Integrations/nodejs_prometheus',
                    label: 'NodeJs',
                },
                {
                    type: 'category',
                    label: 'Operating Systems',
                    collapsed: true,
                    items: [
                        {
                            type: 'category',
                            label: 'Linux',
                            link: {
                                type: 'doc',
                                id: 'Integrations/os/linux/overview',
                            },
                            collapsed: true,
                            items: [
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/linux/sfagent_linux',
                                    label: 'sfAgent Installation on Linux',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/linux/linux_os',
                                    label: 'Monitoring Linux OS',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/linux/cpuloadstats_plugin',
                                    label: 'CPU Load',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/linux/filestats_plugin',
                                    label: 'File Stats',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/linux/netstat',
                                    label: 'Netstat',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/linux/psutil',
                                    label: 'PSUtil',
                                },
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/linux/lsof',
                                    label: 'LSOF',
                                },

                            ],
                        },
                        {
                            type: 'category',
                            label: 'Windows',
                            collapsed: true,
                            items: [
                                {
                                    type: 'doc',
                                    id: 'Integrations/os/windows/sfagent_windows',
                                    label: 'sfAgent installation on Windows',
                                },
                            ],
                        },
                    ],
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/oracleASH',
                    label: 'Oracle ASH',
                },
				{
                    type: 'category',
                    label: 'PgBouncer', 
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/pgBouncer/pgBouncer_on_instance',
                            label: 'PgBouncer on Instance'
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Postgres',
                    link: {
                        type: 'doc',
                        id: 'Integrations/postgres/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/postgres/postgres_instances',
                            label: 'Instances',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/postgres/postgres_kubernetes',
                            label: 'Kubernetes',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/postgres/postgres_sfpoller',
                            label: 'AWS RDS',
                        },
                    ],
                },
                
                {
                    type: 'category',
                    label: 'RabbitMQ',
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/rabbitmqinstance',
                            label: 'RabbitMQ on Instances',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/rabbitmqkubernet',
                            label: 'RabbitMQ in Kubernetes',
                        },
                    ]
                }, 
                {
                    type: 'doc',
                    id: 'Integrations/redis_sentinel',
                    label: 'Redis Sentinel',
                },
                {
                    type: 'category',
                    label: 'Redis',
                    link: {
                        type: 'doc',
                        id: 'Integrations/redis/overview'
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/redis/redis_instance',
                            label: 'Redis Instance',
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/redis/redis_kubernetes',
                            label: 'Redis Kubernetes',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'StatsD',
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/statsd/custom_monitoring',
                            label: 'Custom Monitoring using StatsD',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Tomcat',
                    link: {
                        type: 'doc',
                        id: 'Integrations/tomcat/overview',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'Integrations/tomcat/tomcat_linux',
                            label: 'Tomcat in Linux'
                        },
                        {
                            type: 'doc',
                            id: 'Integrations/tomcat/tomcat_windows',
                            label: 'Tomcat in Windows'
                        },
                    ]
                },
                {
                    type: 'doc',
                    id: 'Integrations/tripwire',
                    label: 'TripWire',
                },
                {
                    type: 'doc',
                    id: 'Integrations/plugin/vcenter',
                    label: 'vCenter',
                },

                {
                    type: 'doc',
                    id: 'Integrations/zookeeper',
                    label: 'ZooKeeper',
                },
				





            ],
        },
        {
            type: 'category',
            label: 'Profiling',

            link: {
                type: 'generated-index',
                title: 'Profiling',
                image: '/img/docusaurus.png',
            },
            items: [
                'Integrations/go/profiler',
                {
                    type: 'category',
                    label: 'Java',
                    link: {
                        type: 'doc',
                        id: 'Integrations/java/java_profiler_cpu',
                    },
                    items: ['Integrations/java/java_profiler_cpu', 'Integrations/java/java_profiler_memory']
                },
            ],
            collapsed: true,
            //   items: ['Integrations/go/profiler', 'Integrations/java/java_profiler_cpu'], 
        },
        {
            type: 'category',
            label: 'Log Management',
            link: {
                type: 'doc',
                id: 'Log_management/log_overview',
            },
            collapsed: true,
            items: [


                {
                    type: 'category',
                    label: 'Feature Extraction',
                    link: {
                        type: 'doc',
                        id: 'Log_management/feature_extraction',
                    },
                    collapsed: false,
                    items: [
                        {
                            type: 'doc',
                            id: 'Log_management/skip_functions',
                            label: 'Skip Functions'
                        },
                        {
                            type: 'doc',
                            id: 'Log_management/extract_functions',
                            label: 'Extract Functions'
                        },
                    ]
                },




                //{
                //   type: 'doc',
                //    id: 'Log_management/feature_extraction',
                //    label: 'Feature Extraction',
                //},
                //{
                //    type: 'doc',
                //    id: 'Log_management/skip_functions',
                //    label: 'Skip Functions',
                //},
                //{
                //   type: 'doc',
                //    id: 'Log_management/extract_functions',
                //    label: 'Extract Functions',
                //},
                {
                    type: 'doc',
                    id: 'Log_management/archival',
                    label: 'Archival',
                },
                {
                    type: 'doc',
                    id: 'Log_management/log_signatures',
                    label: 'Log Signatures',
                },
                {
                    type: 'doc',
                    id: 'Log_management/etl_jobs',
                    label: 'ETL Jobs',
                },
                {
                    type: 'doc',
                    id: 'Log_management/custom_log',
                    label: 'Custom Log Overview',
                },
				{
                    type: 'doc',
                    id: 'Log_management/custom_log_parser',
                    label: 'Custom Log Parser',
                },
            ],
        },
        {
            type: 'category',
            label: 'Dashboards',
            link: {
                type: 'generated-index',
                title: 'Dashboards'
            },
            collapsed: true,
            items: [
			    'Dashboards/getting_started', 
                'Dashboards/dashboard_management',
		        {
                    type: 'category',
                    label: 'dashboard_customization',
                        collapsed: true,
                        items: [
						    {
                                type: 'doc',
                                id: 'Dashboards/dashboard_customization/creating_components',
                                label: 'Creating Components',
                            },
							    ],
				},
                {
                    type: 'category',
                    label: 'Components',
                    // link: {
                    //     type: 'doc',
                    //     id: 'Dashboards/Components/table',
                    // },
                    items: [
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/table',
                            label: 'Table'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/drop_down',
                            label: 'Drop Down'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/tabbed_table',
                            label: 'Tabbed Table'
                        },

                        {
                            type: 'doc',
                            id: 'Dashboards/Components/bar_chart',
                            label: 'Bar Chart'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/bar_chart_histo',
                            label: 'Bar Chart Histogram'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/line_chart',
                            label: 'Line Chart'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/key_based_line',
                            label: 'Key Based Line Chart'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/pie_chart',
                            label: 'Pie Chart'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/distribution',
                            label: 'Distribution Chart'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/summary_box',
                            label: 'Summary Box'
                        },
                        {
                            type: 'doc',
                            id: 'Dashboards/Components/excel_table',
                            label: 'Excel Table'
                        },
                    ]
                }
            ],
        },
        {
            type: 'category',
            label: 'Alerts & Notifications',
            link: {
                type: 'doc',
                id: 'Alerts_notifications/getting_started',
            },
            collapsed: true,
            items: [ 
				{
                    type: 'category',
                    label: 'Notifications',
					link: {
						type: 'doc',
						id: 'Alerts_notifications/Notifications/introduction',
					},
                    collapsed: true,  
                          items: [
						       {
                                   type: 'doc',
                                   id: 'Alerts_notifications/Notifications/introduction',
                                   label: 'Introduction',
                               },
							   {
                                   type: 'category',
                                   label: 'Step 1: Create Notification Channel', 
                                    collapsed: true,
                                         items: [
						                     {
                                                type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Create_Notification_Channel/email',
                                                label: 'Email',
                                             },
											 {
												type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Create_Notification_Channel/zenduty',
                                                label: 'Zenduty',
											 },
											 {
												type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Create_Notification_Channel/opsGenie',
                                                label: 'Opsgenie',
											 },
											 {
												type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Create_Notification_Channel/slack',
                                                label: 'Slack',
											 },
											 {
												type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Create_Notification_Channel/teams',
                                                label: 'Teams',
											 },
											 {
												type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Create_Notification_Channel/webhook',
                                                label: 'Webhook',
											 },
											 {
												type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Create_Notification_Channel/pagerDuty',
                                                label: 'PagerDuty',
											 },
											 ],
							   },
						       
						                     {
                                                type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Map_Notification_Alerts/map_projects_to_channels',
                                                label: 'Step 2: Add Notification Channel to Project',
                                             },
											 {
												type: 'doc',
                                                id: 'Alerts_notifications/Notifications/Map_Notification_Alerts/alert_mapping',
                                                label: 'Step 3: Map Alerts to Notification Channels',
											 },
										
							   ],
				},
            ],
		
        },
        {
            type: 'category',
            label: 'Real User Monitoring',
            link: {
                type: 'doc',
                id: 'RUM/RUM_documentation',
            },
            collapsed: true,
            items: [
                {
                    type: 'category',
                    label: 'Agent Installation',
                    link: {
                        type: 'doc',
                        id: 'RUM/RUM_agent_installation',
                    },
                    collapsed: true,
                    items: [
                        {
                            type: 'category',
                            label: 'Angular',
                            link: {
                                type: 'doc',
                                id: 'RUM/agent_installation/angular_12x',
                            },
                            collapsed: true,
                            items: [
                                {
                                    type: 'doc',
                                    id: 'RUM/agent_installation/angular_12x',
                                    label: 'Version 12.x and below'
                                },
                                {
                                    type: 'doc',
                                    id: 'RUM/agent_installation/angular_13x',
                                    label: 'Version 13.x and above'
                                },
                            ]
                        },
                        {
                            type: 'doc',
                            id: 'RUM/agent_installation/react',
                            label: 'React'
                        },
                        {
                            type: 'doc',
                            id: 'RUM/agent_installation/nextjs',
                            label: 'Nextjs'
                        },
                        {
                            type: 'doc',
                            id: 'RUM/agent_installation/others',
                            label: 'Others'
                        }
                    ]
                },
                {
                    type: 'doc',
                    id: 'RUM/RUM_Dashboard',
                    label: 'RUM Dashboard',
                },
                {
                    type: 'doc',
                    id: 'RUM/RUM_Metrics',
                    label: 'Performance Metrics',
                },
                {
                    type: 'doc',
                    id: 'RUM/RUM_Glossary',
                    label: 'Glossary',
                }
            ],
        },
        {
            type: 'category',
            label: 'Synthetic Monitoring',
            link: {
                type: 'doc',
                id: 'Synthetic/overview',
            },
            collapsed: true,
            items: [
                {
                    type: 'doc',
                    label: 'Overview',
                    id: 'Synthetic/overview',
                }

            ],
        },
        {
            type: 'category',
            label: 'Security Information and Event Management',
            link: {
                type: 'doc',
                id: 'SIEM/SIEM_documentation',
            },
            collapsed: true,
            items: [
                {
                    type: 'doc',
                    id: 'SIEM/siemappliance_installation',
                    label: 'SIEM Appliance Installation',
                },
                {
                    type: 'doc',
                    label: 'SIEM Agent Installation',
                    id: 'SIEM/siemagent_installation',
                },
                {
                    type: 'doc',
                    id: 'SIEM/SIEM_events',
                    label: 'SIEM Events',
                },
                
            ],
        },
		{
            type: 'category',
            label: 'Release Notes',
            link: {
                type: 'doc',
                id: 'release_note/overview'
            },
            collapsed: true,
            items: [
				{
                    type: 'category',
                    label: 'Database',
					link: {
						type: 'doc',
						id: 'release_note/database/postgres',
					},
                    collapsed: true,  
                          items: [
						       {
                                   type: 'doc',
                                   id: 'release_note/database/postgres',
							       label: 'Postgres',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/aurora',
							       label: 'Aurora',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/docdb',
							       label: 'DocumentDB',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/azureDB',
							       label: 'AzureDB',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/redis',
							       label: 'Redis',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/mysql',
							       label: 'MySQL',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/mssql',
							       label: 'MSSQL',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/clickhouse',
							       label: 'Clickhouse',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/aws_rds',
							       label: 'AWS RDS',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/mongodB',
							       label: 'MongoDB',
							   },
							   {
                                   type: 'doc',
                                   id: 'release_note/database/oracle_ash',
							       label: 'Oracle ASH',
							   },
							   
							],
							
					    
				},
                
            ],			
        },

    ],
};
